#!/usr/bin/python
# -*- coding: <utf-8> -*-

import random, time, sys
import wordPatterns, wordLengths, entryList

def tprint(message, end='\n'):
    for c in message:
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.randint(40, 100)/ 1000)
    sys.stdout.write(end)


tprint('\n   ' + ' ' * 4 + 'a gaoyaoxin app' + ' ' * 4 + '   \n')
print('This is a game to find a word with the same pattern as the word generated by computer using the word length you input. For instance, if you input 4 as word length, word "well" might be generated and you need to find a word with the same pattern, such as "full" (both having the pattern 0.1.2.2, with only the third and fourth letters being the same).')

def getWordPattern(word):
	# Returns a string of the pattern form of the given word.
	# e.g. '0.1.2.3.4.1.2.3.5.6' for 'DUSTBUSTER'
	word = word.upper()
	nextNum = 0
	letterNums = {}
	wordPattern = []

	for letter in word:
		if letter not in letterNums:
			letterNums[letter] = str(nextNum)
			nextNum += 1
		wordPattern.append(letterNums[letter])
	return '.'.join(wordPattern)



def generateWord(wordLength):
	#global wordGenerated
	wordGenerated = wordLengths.allLengths[wordLength][random.randint(0, len(wordLengths.allLengths[wordLength]) - 1)]
	print(wordGenerated.lower())
	return wordGenerated

def getWordGeneratedPattern():
	
	wordGeneratedPattern = getWordPattern(wordGenerated)
	print(wordGenerated.lower())
	return wordGenerated


def main():
	wordLengthInput = input('Please input word length (3-22, 28):\n> ')
	wordLengthInput = int(wordLengthInput)

	generateWord(wordLengthInput)
	startTime = time.time()
	userAnswerWord = input('Please input a word with the same pattern or 0 if no word meets the requirement.\n> ')

	userAnswerWordPattern = getWordPattern(userAnswerWord)

	allTime = time.time() - startTime
	allTime = round(allTime, 2)
	print('Time you used: ' + str(allTime) + 's')

	if userAnswerWordPattern == wordGeneratedPattern and userAnswerWord.upper() in entryList.wordList:
		print('You win!')
	elif userAnswerWordPattern == wordGeneratedPattern and (userAnswerWord.upper() not in entryList.wordList):
		print('You lose! The word you input is not English!')
	elif userAnswerWord == '0':
		allOtherPossibleWordsInThisPattern = (wordPatterns.allPatterns[wordGeneratedPattern])
		allOtherPossibleWordsInThisPattern.remove(wordGenerated)
#		print(allOtherPossibleWordsInThisPattern)
		if len(allOtherPossibleWordsInThisPattern) == 0:
			print('You win! There is no other word in this pattern.')
		else:
			print('You lose! There are other words in this pattern:')
			print('\n' + (', '.join(allOtherPossibleWordsInThisPattern)).lower() + '\n')
	elif userAnswerWordPattern != wordGeneratedPattern:
		print('You lose! The word you typed is not the same pattern as the given one.')
	
while 1:
	main()